SELECT DISTINCT ?Name ?Address ?Description ?Longitude ?Latitude (year(?inception) as ?TimeStamp) 
WHERE {
  SERVICE wikibase:label { 
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". 
    ?band rdfs:label ?Name .
    ?band schema:description ?Description .
    ?place rdfs:label ?Address.
  }
  ?band wdt:P136 wd:Q3071.
  ?band wdt:P31 wd:Q215380.
  ?band wdt:P740 ?place.
  ?place p:P625 ?coordinate.
  ?coordinate psv:P625 ?coordinate_node.
  ?coordinate_node wikibase:geoLatitude ?Latitude.
  ?coordinate_node wikibase:geoLongitude ?Longitude.
  ?band wdt:P571 ?inception.
}

